### ISSUE TITLE
Add Microwindows / Nano-X

### ISSUE THREAD

**Issue by niutech** [shmup/awesome-cosmopolitan#6]
Microwindows / Nano-X Window System has added support for Cosmopolitan build, please include it: https://github.com/ghaerr/microwindows

You can see the demo [here](https://github.com/jart/cosmopolitan/issues/35#issuecomment-1098659862).

**Comment by shmup** [comment]
Thanks. Closed with https://github.com/shmup/awesome-cosmopolitan/commit/c35907e42b1a8f7e22ac22db0bf56afa66505174

https://github.com/shmup/awesome-cosmopolitan#projects
